backend:
  name: github
  repo: alvarosaavedra/amcai # Path to your Github repository
  branch: master # Branch to update
  #site_domain: astronomer-hare-58113.netlify.com # Your Netlify site address if different from host
media_folder: "contents/images/uploads"
collections:
    - name: 'descriptions'
      label: Descripciones
      folder: "contents/descriptions"
      create: true
      fields:
        - {label: "Titulo", name: "title", widget: "string"}
        - {label: "Posicion", name: "order", widget: "number"}
        - {label: "Texto", name: "body", widget: "markdown"}
    - name: 'testimonials'
      label: Testimonios
      folder: "contents/testimonials"
      create: true
      fields:
        - {label: "Titulo", name: "title", widget: "string"}
        - {label: "Posicion", name: "order", widget: "number"}
        - {label: "Texto", name: "body", widget: "markdown"}
    - name: 'endings'
      label: Finales
      folder: "contents/endings"
      create: true
      fields:
        - {label: "Titulo", name: "title", widget: "string"}
        - {label: "Posicion", name: "order", widget: "number"}
        - {label: "Texto", name: "body", widget: "markdown"}